# Generated by Django 2.1.7 on 2019-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app27', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='idno',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
        ),
    ]
