# Generated by Django 2.1.7 on 2019-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('un', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('up', models.CharField(max_length=20)),
            ],
        ),
    ]
