# Generated by Django 2.1.7 on 2019-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='emoloyee/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='user/')),
            ],
        ),
    ]
